name: polinac_web
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.0-82.0.dev <4.0.0'

dependencies:
  firebase_auth: ^4.20.0
  firebase_core: ^2.32.0
  # See https://github.com/pichillilorenzo/flutter_inappwebview/issues/1468#issuecomment-2002170180
  flutter:
    sdk: flutter
  flutter_inappwebview_web: ^1.0.8
  flutter_markdown: ^0.7.1
  google_fonts:  ^6.2.1
  url_launcher: ^6.2.6
  url_strategy: ^0.2.0

dev_dependencies:
  dart_flutter_team_lints: ^2.1.0
  flutter_launcher_icons: "^0.13.1"
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/polina.jpg
    - assets/images/molokai.jpg

flutter_launcher_icons:
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#FFFFFF"
    theme_color: "#FFC107"
